# Generated by Django 4.1.7 on 2023-03-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('clients_quantity', models.IntegerField(blank=True)),
                ('residence', models.CharField(blank=True, max_length=50)),
                ('phone', models.IntegerField(blank=True)),
            ],
        ),
    ]
