# Generated by Django 4.1.7 on 2023-03-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingdjangoProject1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stay_duration',
            field=models.IntegerField(blank=True, default='7'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='residence',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
